
package UI;
import Controller.Controller;
import arquiproject.OtherMain;
import java.awt.Color;

public class MainUI extends javax.swing.JFrame {
    Controller controller;
    
    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initComponents();
        /**/
    }
    
    Thread ciclo = new Thread(){
        public void run(){
            cicloCheck();
        }
    };
    
    
    public void cicloCheck(){
        String serial;
        StringBuilder nuevoSerial;
        int potenciometro;
        boolean botonSalir;
        boolean botonEntrar;
        while (true){
            
            serial = controller.getSerial();
            potenciometro = controller.interpretarPotenciometro(serial);
            System.out.println(potenciometro+"\n");
            botonSalir = controller.interpretarBotonSalir(serial.charAt(7));
            botonEntrar = controller.interpretarBotonEntrar(serial.charAt(8));
            switch (potenciometro){
                case 0:
                    this.temperature_btn.setBackground(Color.red);
                    this.grade_btn.setBackground(Color.black);
                    this.exit_btn.setBackground(Color.black);
                    break;
                case 1:
                    this.grade_btn.setBackground(Color.red);
                    this.exit_btn.setBackground(Color.black);
                    this.temperature_btn.setBackground(Color.black);
                    break;
                case 2:
                    this.exit_btn.setBackground(Color.red);
                    this.grade_btn.setBackground(Color.black);
                    this.temperature_btn.setBackground(Color.black);
                    break;
            }

            if (botonSalir==true){
                this.dispose();
            }
            if (botonEntrar==true){
                switch (potenciometro){
                    case 0:
                        new VentanaTemperatura(controller).setVisible(true);
                        nuevoSerial = new StringBuilder(controller.getSerial());
                        nuevoSerial.setCharAt(8, '0');
                        controller.setSerial(nuevoSerial.toString());
                        break;
                    case 1:
                        new VentanaEnviarCalificacion().setVisible(true);
                        nuevoSerial = new StringBuilder(controller.getSerial());
                        nuevoSerial.setCharAt(8, '0');
                        controller.setSerial(nuevoSerial.toString());
                        break;
                    case 2:
                        System.exit(0);
                        this.dispose();
                        break;
                }
            }
            try {
                Thread.sleep(50);
            }catch(InterruptedException e){
                System.out.println("Waiting...");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcome_lbl = new javax.swing.JLabel();
        grade_btn = new javax.swing.JButton();
        exit_btn = new javax.swing.JButton();
        temperature_btn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btnStart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        welcome_lbl.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        welcome_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcome_lbl.setText("Bienvenido");
        welcome_lbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        welcome_lbl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        grade_btn.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        grade_btn.setText("Enviar Califiación");
        grade_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grade_btnActionPerformed(evt);
            }
        });

        exit_btn.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        exit_btn.setText("Salir");
        exit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_btnActionPerformed(evt);
            }
        });

        temperature_btn.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        temperature_btn.setText("Mostrar Temperatura");
        temperature_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temperature_btnActionPerformed(evt);
            }
        });

        jButton1.setText("Enter");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Izquierda");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Medio");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Derecha");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(welcome_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(temperature_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                                .addComponent(grade_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(exit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnStart)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {exit_btn, grade_btn, temperature_btn});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnStart)
                .addGap(9, 9, 9)
                .addComponent(welcome_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grade_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(temperature_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {exit_btn, grade_btn, temperature_btn});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void temperature_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temperature_btnActionPerformed
        //Botón Mostrar temperatura:
        new VentanaTemperatura().setVisible(true);
    }//GEN-LAST:event_temperature_btnActionPerformed

    private void grade_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grade_btnActionPerformed
        //Botón Enviar calificación:
        new VentanaEnviarCalificacion().setVisible(true);
    }//GEN-LAST:event_grade_btnActionPerformed

    private void exit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_btnActionPerformed
        //Botón Salir:
        this.dispose();
    }//GEN-LAST:event_exit_btnActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
    }//GEN-LAST:event_formWindowActivated

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        StringBuilder nuevoSerial = new StringBuilder(controller.getSerial());
        nuevoSerial.setCharAt(8, '1');
        controller.setSerial(nuevoSerial.toString());
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        StringBuilder nuevoSerial = new StringBuilder(controller.getSerial());
        nuevoSerial.setCharAt(4, '0');
        nuevoSerial.setCharAt(5, '8');
        nuevoSerial.setCharAt(6, '5');
        controller.setSerial(nuevoSerial.toString());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        StringBuilder nuevoSerial = new StringBuilder(controller.getSerial());
        nuevoSerial.setCharAt(4, '1');
        nuevoSerial.setCharAt(5, '5');
        nuevoSerial.setCharAt(6, '0');
        controller.setSerial(nuevoSerial.toString());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        StringBuilder nuevoSerial = new StringBuilder(controller.getSerial());
        nuevoSerial.setCharAt(4, '2');
        nuevoSerial.setCharAt(5, '5');
        nuevoSerial.setCharAt(6, '0');
        controller.setSerial(nuevoSerial.toString());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        ciclo.start();
    }//GEN-LAST:event_btnStartActionPerformed

    //NUESTRAS FUNCIONES
    public void setController(Controller controller){
        this.controller = controller;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.JButton exit_btn;
    private javax.swing.JButton grade_btn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton temperature_btn;
    private javax.swing.JLabel welcome_lbl;
    // End of variables declaration//GEN-END:variables
}
